---
- name: Create Mirror Directories
  become: yes
  become_user: frappe
  file:
    path: /home/frappe/ubuntu/
    state: directory
    mode: 0755

- name: Install apt-mirror
  apt:
    package: apt-mirror
    state: present

- name: Test for apt-mirror access via frappe user
  shell: grep -c "apt-mirror" /etc/sudoers.d/frappe || true
  register: apt_mirror_permissions

- name: Update sudoers
  lineinfile:
    dest: /etc/sudoers.d/frappe
    line: 'frappe ALL = (root) NOPASSWD: /usr/bin/apt-mirror'
  when: apt_mirror_permissions.stdout == '0'

- name: Backup Mirror List
  copy:
    src: /etc/apt/mirror.list
    dest: /etc/apt/mirror.list-back
    remote_src: true

- name: Setup mirror config
  template:
    src: mirror.list.j2
    dest: /etc/apt/mirror.list

- name: Start mirroring
  become: yes
  become_user: frappe
  shell: 'nohup apt-mirror > nohup.out 2>&1 &'
  args:
    chdir: /home/frappe
    executable: /bin/bash