pull_request_rules:
  - name: backport to develop
    conditions:
      - label="backport-develop"
    actions:
      backport:
        branches:
          - develop
        assignees:
          - "{{ author }}"
  
  - name: backport to master
    conditions:
      - label="backport-master"
    actions:
      backport:
        branches:
          - master
        assignees:
          - "{{ author }}"

