coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 75%
        threshold: 0%
        if_ci_failed: ignore
      ignore:
        - press/press/report/**
