---
- name: Unmount Shared
  ansible.builtin.mount:
    path: "{{ shared_directory }}"
    state: unmounted

- name: Remove fstab entry for shared_directory
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^\S+\s+{{ shared_directory }}\s+'

- name: Delete Shared Directory
  ansible.builtin.file:
    path: "{{ shared_directory }}"
    state: absent
