---

- name: Create log folder
  file:
    path: /var/log/ssh_sessions
    owner: frappe
    mode: u=rwX,g=rX,o=rX
    recurse: yes
    state: directory

- name: Configure session recording
  copy:
    src: record_ssh_session.j2
    dest: /etc/profile.d/record_ssh_session.sh

