---
- name: Create Benches Directory
  become: yes
  become_user: frappe
  file:
    dest: /home/frappe/benches
    state: directory

- name: Install MariaDB Client
  apt:
    pkg:
      - mariadb-client
    state: present
