# Copyright (c) 2026, Frappe and contributors
# For license information, please see license.txt

from dataclasses import asdict, dataclass

import frappe
from frappe.model.document import Document
from frappe.model.naming import make_autoname


@dataclass
class CheckResult:
	check_id: str
	check_name: str
	category: str
	result: str
	severity: str = ""
	message: str = ""
	details: str = ""
	remediation: str = ""


class MarketplaceAppAudit(Document):
	# begin: auto-generated types
	# This code is auto-generated. Do not modify anything in this block.

	from typing import TYPE_CHECKING

	if TYPE_CHECKING:
		from frappe.types import DF

		from press.marketplace.doctype.marketplace_app_audit_checks.marketplace_app_audit_checks import (
			MarketplaceAppAuditChecks,
		)

		app_release: DF.Link
		approval_request: DF.Link | None
		audit_checks: DF.Table[MarketplaceAppAuditChecks]
		audit_result: DF.Literal["Pass", "Needs Improvement", "Warn", "Fail", "Inconclusive"]
		audit_summary: DF.LongText | None
		audit_type: DF.Literal["", "Release Change", "Submission Gate", "Manual Run", "Scheduled Audit"]
		error_traceback: DF.LongText | None
		finished_at: DF.Datetime | None
		marketplace_app: DF.Link
		started_at: DF.Datetime | None
		status: DF.Literal["Queued", "Running", "Completed", "Failed"]
		team: DF.Link | None
	# end: auto-generated types

	def autoname(self):
		# AUD-{marketplace_app}-.#####
		series = f"AUD-{self.marketplace_app}-.#####"
		self.name = make_autoname(series)

	@staticmethod
	def create_for_release(
		marketplace_app: str,
		app_release: str,
		approval_request: str | None = None,
		audit_type: str = "Release Change",
	) -> "MarketplaceAppAudit | None":
		# For Release Change: reuse the single existing audit per marketplace app
		# reason: on every new commit, a new release is being created, we don't want to create new records for every new release.
		# we can reuse the existing audit record and update the release.
		if audit_type == "Release Change":
			existing = frappe.db.get_value(
				"Marketplace App Audit",
				{"marketplace_app": marketplace_app, "audit_type": "Release Change"},
				["name", "status"],
				as_dict=True,
			)
			if existing:
				if existing.status == "Running":
					return None

				audit = frappe.get_doc("Marketplace App Audit", existing.name)
				audit.app_release = app_release
				audit.status = "Queued"
				audit.audit_result = ""
				audit.audit_summary = ""
				audit.error_traceback = ""
				audit.audit_checks = []
				audit.save()
				audit.trigger_audit()
				return audit

		audit = frappe.new_doc("Marketplace App Audit")
		audit.marketplace_app = marketplace_app
		audit.app_release = app_release
		audit.approval_request = approval_request
		audit.audit_type = audit_type
		audit.status = "Queued"
		audit.team = frappe.db.get_value("Marketplace App", marketplace_app, "team")
		audit.insert()
		audit.trigger_audit()
		return audit

	def trigger_audit(self):
		"""
		This will trigger the run_audit method in background job.
		"""

		frappe.enqueue_doc(
			self.doctype,
			self.name,
			"run_audit",
			queue="long",
			timeout=3600,
			enqueue_after_commit=True,
		)

	def run_audit(self):
		self.started_at = frappe.utils.now_datetime()
		self.status = "Running"
		self.save()

		try:
			# run all the audit checking functions here(execute_audit_checks)
			# compute the results generated by the execute_audit_checks functions
			results = self.execute_audit_checks()
			self.populate_audit_checks(results)
			self.compute_results()
			self.status = "Completed"
		except Exception:
			self.status = "Failed"
			self.audit_result = "Inconclusive"
			self.audit_summary = "Audit failed due to an unexpected error."
			# log the error traceback
			self.error_traceback = frappe.get_traceback(with_context=True)
		finally:
			self.finished_at = frappe.utils.now_datetime()
			self.save()

	@frappe.whitelist()
	def rerun_audit(self):
		self.status = "Queued"
		self.save()
		frappe.enqueue_doc(
			self.doctype,
			self.name,
			"run_audit",
			queue="long",
			timeout=3600,
			enqueue_after_commit=True,
		)

	def execute_audit_checks(self):
		"""
		Execute all the necessary audit checks here.
		Each check is a separate function which specifically checks for one particular aspect only -
		like metadata, versioning, dependencies, code quality, security, compatibility, operational.

		"""
		marketplace_app = frappe.get_doc("Marketplace App", self.marketplace_app)
		release = frappe.get_doc("App Release", self.app_release)
		release._clone()
		clone_dir = release.clone_directory
		results = []

		from press.marketplace.doctype.marketplace_app_audit.checks.code_quality import (
			run_code_quality_checks,
		)
		from press.marketplace.doctype.marketplace_app_audit.checks.dependencies import run_dependency_checks
		from press.marketplace.doctype.marketplace_app_audit.checks.metadata import run_metadata_checks
		from press.marketplace.doctype.marketplace_app_audit.checks.versioning import run_versioning_checks

		results.extend(run_metadata_checks(marketplace_app))
		results.extend(run_versioning_checks(clone_dir))
		results.extend(run_dependency_checks(clone_dir))
		results.extend(run_code_quality_checks(clone_dir))
		return results

	def populate_audit_checks(self, results: list[CheckResult]):
		self.audit_checks = []
		for result in results:
			self.append("audit_checks", asdict(result))

	def compute_results(self):
		"""
		Compute the overall result of the audit based on the results of the audit checks.

		Severity: "How bad is it if this fails?"
		Result: "Did it actually fail for this app?"

		"""
		tally = self._tally_checks()
		self.audit_result = self._determine_overall_result(tally)
		self.audit_summary = self._build_summary(tally)

	def _tally_checks(self) -> dict:
		"""
		Count check results grouped by severity.

		Returns:
			{
				"Critical": {"Pass": 1, "Fail": 2, "Warn": 0, "Skipped": 0, "Error": 0},
				"Major":    {"Pass": 3, "Fail": 1, "Warn": 2, "Skipped": 0, "Error": 0},
				"Minor":    {"Pass": 4, "Fail": 0, "Warn": 1, "Skipped": 0, "Error": 0},
				"Info":     {"Pass": 2, "Fail": 0, "Warn": 0, "Skipped": 0, "Error": 0},
				"totals":   {"Pass": 10, "Fail": 3, "Warn": 3, "Skipped": 0, "Error": 0},
			}
		"""
		severities = ("Critical", "Major", "Minor", "Info")
		results = ("Pass", "Fail", "Warn", "Skipped", "Error")

		tally = {s: {r: 0 for r in results} for s in severities}
		tally["totals"] = {r: 0 for r in results}

		for check in self.audit_checks:
			severity = check.severity
			result = check.result
			if severity in tally and result in tally[severity]:
				tally[severity][result] += 1
				tally["totals"][result] += 1

		return tally

	def _determine_overall_result(self, tally: dict) -> str:
		"""
		Deterministic priority chain (first match wins):
		1. Any Critical Fail   -> "Fail"
		2. Any Major Fail/Warn -> "Warn"
		3. Any Minor Fail/Warn -> "Needs Improvement"
		4. Otherwise            -> "Pass"
		"""
		crit = tally["Critical"]
		major = tally["Major"]
		minor = tally["Minor"]

		if crit["Fail"] > 0:
			return "Fail"
		if major["Fail"] > 0 or major["Warn"] > 0:
			if major["Fail"] >= major["Warn"]:
				return "Fail"
			return "Warn"
		if minor["Fail"] > 0 or minor["Warn"] > 0:
			return "Needs Improvement"
		return "Pass"

	def _build_summary(self, tally: dict) -> str:
		"""
		Readable breakdown for the reviewer.
		"""
		totals = tally["totals"]
		total_checks = sum(totals.values())

		lines = []
		lines.append(
			f"{total_checks} checks run: "
			f"{totals['Pass']} passed, {totals['Fail']} failed, "
			f"{totals['Warn']} warnings, {totals['Skipped']} skipped, "
			f"{totals['Error']} errors"
		)

		for severity in ("Critical", "Major", "Minor", "Info"):
			s = tally[severity]
			issues = s["Fail"] + s["Warn"]
			if issues > 0:
				lines.append(f"  {severity}: {s['Fail']} failed, {s['Warn']} warnings")

		return "\n".join(lines)
