# Copyright (c) 2026, Frappe and contributors
# For license information, please see license.txt

import json
from dataclasses import asdict, dataclass

import frappe
from frappe.model.document import Document
from frappe.model.naming import make_autoname


@dataclass
class CheckResult:
	check_id: str
	check_name: str
	category: str
	result: str
	severity: str = ""
	message: str = ""
	details: str = ""
	remediation: str = ""
	is_internal_only: bool = False
	is_blocking: bool = False


class MarketplaceAppAudit(Document):
	# begin: auto-generated types
	# This code is auto-generated. Do not modify anything in this block.

	from typing import TYPE_CHECKING

	if TYPE_CHECKING:
		from frappe.types import DF

		from press.marketplace.doctype.marketplace_app_audit_checks.marketplace_app_audit_checks import (
			MarketplaceAppAuditChecks,
		)

		app_release: DF.Link
		approval_request: DF.Link | None
		audit_checks: DF.Table[MarketplaceAppAuditChecks]
		audit_result: DF.Literal["Pass", "Needs Improvement", "Warn", "Fail", "Inconclusive"]
		audit_summary: DF.LongText | None
		audit_type: DF.Literal["", "Release Change", "Submission Gate", "Manual Run", "Scheduled Audit"]
		error_traceback: DF.LongText | None
		finished_at: DF.Datetime | None
		marketplace_app: DF.Link
		started_at: DF.Datetime | None
		status: DF.Literal["Queued", "Running", "Completed", "Failed"]
		team: DF.Link | None
	# end: auto-generated types

	def autoname(self):
		# AUD-{marketplace_app}-.#####
		series = f"AUD-{self.marketplace_app}-.#####"
		self.name = make_autoname(series)

	@staticmethod
	def create_for_release(
		marketplace_app: str,
		app_release: str,
		approval_request: str | None = None,
		audit_type: str = "Release Change",
	) -> "MarketplaceAppAudit | None":
		# For Release Change: reuse the single existing audit per marketplace app
		# reason: on every new commit, a new release is being created, we don't want to create new records for every new release.
		# we can reuse the existing audit record and update the release.
		if audit_type == "Release Change":
			existing = frappe.db.get_value(
				"Marketplace App Audit",
				{"marketplace_app": marketplace_app, "audit_type": "Release Change"},
				["name", "status"],
				as_dict=True,
			)
			if existing:
				if existing.status == "Running":
					return None

				audit = frappe.get_doc("Marketplace App Audit", existing.name)
				audit.app_release = app_release
				audit.status = "Queued"
				audit.audit_result = ""
				audit.audit_summary = ""
				audit.error_traceback = ""
				audit.audit_checks = []
				audit.save()
				audit.trigger_audit()
				return audit

		audit = frappe.new_doc("Marketplace App Audit")
		audit.marketplace_app = marketplace_app
		audit.app_release = app_release
		audit.approval_request = approval_request
		audit.audit_type = audit_type
		audit.status = "Queued"
		audit.team = frappe.db.get_value("Marketplace App", marketplace_app, "team")
		audit.insert()
		audit.trigger_audit()
		return audit

	def trigger_audit(self):
		"""
		This will trigger the run_audit method in background job.
		"""

		frappe.enqueue_doc(
			self.doctype,
			self.name,
			"run_audit",
			queue="long",
			timeout=3600,
			enqueue_after_commit=True,
		)

	def run_audit(self):
		self.started_at = frappe.utils.now_datetime()
		self.status = "Running"
		self.save()

		try:
			# run all the audit checking functions here(execute_audit_checks)
			# compute the results generated by the execute_audit_checks functions
			results = self.execute_audit_checks()
			self.populate_audit_checks(results)
			self.compute_results()
			self.status = "Completed"
		except Exception:
			self.status = "Failed"
			self.audit_result = "Inconclusive"
			self.audit_summary = "Audit failed due to an unexpected error."
			# log the error traceback
			self.error_traceback = frappe.get_traceback(with_context=True)
		finally:
			self.finished_at = frappe.utils.now_datetime()
			self.save()
			self._handle_audit_outcome()

	@frappe.whitelist()
	def rerun_audit(self):
		self.status = "Queued"
		self.save()
		frappe.enqueue_doc(
			self.doctype,
			self.name,
			"run_audit",
			queue="long",
			timeout=3600,
			enqueue_after_commit=True,
		)

	def execute_audit_checks(self):
		"""
		Execute all the necessary audit checks here.
		Each check is a separate function which specifically checks for one particular aspect only -
		like metadata, versioning, dependencies, code quality, security, compatibility, operational.

		"""
		marketplace_app = frappe.get_doc("Marketplace App", self.marketplace_app)
		release = frappe.get_doc("App Release", self.app_release)
		release._clone()
		clone_dir = release.clone_directory
		results = []

		from press.marketplace.doctype.marketplace_app_audit.checks.code_quality import (
			run_code_quality_checks,
		)
		from press.marketplace.doctype.marketplace_app_audit.checks.compatibility import (
			run_compatibility_checks,
		)
		from press.marketplace.doctype.marketplace_app_audit.checks.dependencies import run_dependency_checks
		from press.marketplace.doctype.marketplace_app_audit.checks.metadata import run_metadata_checks
		from press.marketplace.doctype.marketplace_app_audit.checks.semgrep_rules import run_semgrep_rules
		from press.marketplace.doctype.marketplace_app_audit.checks.versioning import run_versioning_checks

		results.extend(run_metadata_checks(marketplace_app))
		results.extend(run_versioning_checks(clone_dir))
		results.extend(run_dependency_checks(clone_dir))
		results.extend(run_code_quality_checks(clone_dir))
		results.extend(run_compatibility_checks(self.marketplace_app, release.source, clone_dir))
		results.extend(run_semgrep_rules(clone_dir))

		return results

	def populate_audit_checks(self, results: list[CheckResult]):
		self.audit_checks = []
		for result in results:
			self.append("audit_checks", asdict(result))

	def compute_results(self):
		"""
		Compute the overall result of the audit based on the results of the audit checks.

		Severity: "How bad is it if this fails?"
		Result: "Did it actually fail for this app?"

		"""
		tally = self._tally_checks()
		self.audit_result = self._determine_overall_result(tally)
		self.audit_summary = self._build_summary(tally)

	def _tally_checks(self) -> dict:
		"""
		Count check results grouped by severity.

		Returns:
			{
				"Critical": {"Pass": 1, "Fail": 2, "Warn": 0, "Skipped": 0, "Error": 0},
				"Major":    {"Pass": 3, "Fail": 1, "Warn": 2, "Skipped": 0, "Error": 0},
				"Minor":    {"Pass": 4, "Fail": 0, "Warn": 1, "Skipped": 0, "Error": 0},
				"Info":     {"Pass": 2, "Fail": 0, "Warn": 0, "Skipped": 0, "Error": 0},
				"totals":   {"Pass": 10, "Fail": 3, "Warn": 3, "Skipped": 0, "Error": 0},
			}
		"""
		severities = ("Critical", "Major", "Minor", "Info")
		results = ("Pass", "Fail", "Warn", "Skipped", "Error")

		tally = {s: {r: 0 for r in results} for s in severities}
		tally["totals"] = {r: 0 for r in results}

		for check in self.audit_checks:
			severity = check.severity
			result = check.result
			if severity in tally and result in tally[severity]:
				tally[severity][result] += 1
				tally["totals"][result] += 1

		return tally

	def _determine_overall_result(self, tally: dict) -> str:
		"""
		Deterministic priority chain (first match wins):
		1. Any Critical Fail   -> "Fail"
		2. Any Major Fail/Warn -> "Warn"
		3. Any Minor Fail/Warn -> "Needs Improvement"
		4. Otherwise           -> "Pass"
		"""
		crit = tally["Critical"]
		major = tally["Major"]
		minor = tally["Minor"]

		if crit["Fail"] > 0:
			return "Fail"
		if major["Fail"] > 0 or major["Warn"] > 0:
			if major["Fail"] >= major["Warn"]:
				return "Fail"
			return "Warn"
		if minor["Fail"] > 0 or minor["Warn"] > 0:
			return "Needs Improvement"
		return "Pass"

	def _build_summary(self, tally: dict) -> str:
		"""
		Readable breakdown for the reviewer.
		"""
		totals = tally["totals"]
		total_checks = sum(totals.values())

		lines = []
		lines.append(
			f"{total_checks} checks run: "
			f"{totals['Pass']} passed, {totals['Fail']} failed, "
			f"{totals['Warn']} warnings, {totals['Skipped']} skipped, "
			f"{totals['Error']} errors"
		)

		for severity in ("Critical", "Major", "Minor", "Info"):
			s = tally[severity]
			issues = s["Fail"] + s["Warn"]
			if issues > 0:
				lines.append(f"  {severity}: {s['Fail']} failed, {s['Warn']} warnings")

		return "\n".join(lines)

	def _handle_audit_outcome(self):
		"""
		This method will ensure that some action is taken on the audit outcome.
		"""
		# first check if enable audit action is enabled in Marketplace settings
		if not frappe.db.get_single_value("Marketplace Settings", "enable_audit_actions"):
			return

		if self.audit_result == "Fail":
			# mark "attention required" status in marketplace app
			frappe.db.set_value("Marketplace App", self.marketplace_app, "status", "Attention Required")
			self._auto_reject_approval_requests()

			# only yank the release if the audit had any hard blocking failures.
			# else the audit fails but we don't want to yank the release
			if self.has_blocking_failures():
				self._yank_release()

	def _yank_release(self) -> None:
		"""
		Yanks the release to prevent deployment on benches.
		Creating a yanked app release record will automatically mark the release as yanked in it's after insert hook.
		"""
		release = frappe.get_doc("App Release", self.app_release)
		if release.status in ("Draft", "Approved"):
			frappe.get_doc(
				doctype="Yanked App Release",
				hash=release.hash,
				parent_app_release=release.name,
				team=release.team,
			).insert()

	def _auto_reject_approval_requests(self) -> None:
		"""
		Auto rejects all open approval requests for the release.
		"""
		open_approval_requests = frappe.get_all(
			"App Release Approval Request",
			filters={"app_release": self.app_release, "status": "Open"},
			pluck="name",
		)
		if not open_approval_requests:
			return

		for approval_request in open_approval_requests:
			request = frappe.get_doc("App Release Approval Request", approval_request)
			request.status = "Rejected"
			request.reason_for_rejection = (
				f"Automated audit failed.\n\n"
				f"Result: {str(self.audit_result).strip()}\n"
				f"Summary: {str(self.audit_summary).strip()}\n\n"
				f"Please review the audit results and fix the issues pointed."
			)
			request.save()

	@frappe.whitelist()
	def send_report_to_publisher(self):
		"""Email the app publisher a structured audit report with all failing checks."""
		marketplace_app_team, marketplace_app_title = frappe.db.get_value(
			"Marketplace App", self.marketplace_app, ["team", "title"]
		)
		publisher_email = frappe.db.get_value("Team", marketplace_app_team, "user")

		cc = []
		if frappe.db.get_single_value("Marketplace Settings", "send_report_to_reviewer"):
			reviewer_email = frappe.db.get_value("User", frappe.session.user, "email")
			cc = [reviewer_email]

		failing_checks = []
		for check in self.audit_checks:
			# internal only checks are not shown to the publisher in the audit report
			if check.is_internal_only:
				continue

			if check.result in ("Fail", "Warn"):
				details_parsed = None
				if check.details:
					details_parsed = json.loads(check.details)
					occurrences = details_parsed.get("occurrences")
					if isinstance(occurrences, list):
						public_occurrences = [occ for occ in occurrences if not occ.get("is_internal_only")]
						if not public_occurrences:
							continue
						details_parsed = {**details_parsed, "occurrences": public_occurrences}
				failing_checks.append(
					{
						"severity": check.severity,
						"check_name": check.check_name,
						"category": check.category,
						"result": check.result,
						"message": check.message,
						"details": details_parsed,
						"remediation": check.remediation,
					}
				)

		frappe.sendmail(
			recipients=[publisher_email],
			cc=cc,
			subject=f"Marketplace Audit Report: {marketplace_app_title}",
			args={
				"app_title": marketplace_app_title,
				"audit_result": self.audit_result,
				"audit_summary": self.audit_summary,
				"failing_checks": failing_checks,
			},
			template="marketplace_audit_report",
		)
		frappe.msgprint(f"Audit report sent to {publisher_email}")

	def has_blocking_failures(self) -> bool:
		"""True if any child row is blocking, or any Semgrep occurrence is marked blocking."""
		for check in self.audit_checks:
			if check.is_blocking:
				return True

			# although we are rolling up the semgrep ruleset's blocking findings to the overall audit check result, we should still check for blocking findings in the semgrep ruleset specifically.
			# if check name starts with "Semgrep" we need to check if it has any blocking findings
			if not check.check_name.startswith("Semgrep") or not check.details:
				continue
			payload = json.loads(check.details)
			occurrences = payload.get("occurrences") or []
			if any(occ.get("is_blocking") for occ in occurrences if isinstance(occ, dict)):
				return True
		return False
