/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}

declare global {
	const LucideActivity: typeof import('~icons/lucide/activity')['default']
	const LucideAlertTriangle: typeof import('~icons/lucide/alert-triangle')['default']
	const LucideArchive: typeof import('~icons/lucide/archive')['default']
	const LucideArrowUpCircle: typeof import('~icons/lucide/arrow-up-circle')['default']
	const LucideBoxes: typeof import('~icons/lucide/boxes')['default']
	const LucideCircleDashed: typeof import('~icons/lucide/circle-dashed')['default']
	const LucideCirclePlus: typeof import('~icons/lucide/circle-plus')['default']
	const LucideCode: typeof import('~icons/lucide/code')['default']
	const LucideCreditCard: typeof import('~icons/lucide/credit-card')['default']
	const LucideDatabaseZap: typeof import('~icons/lucide/database-zap')['default']
	const LucideEarth: typeof import('~icons/lucide/earth')['default']
	const LucideFileSearch: typeof import('~icons/lucide/file-search')['default']
	const LucideGlobe: typeof import('~icons/lucide/globe')['default']
	const LucideKey: typeof import('~icons/lucide/key')['default']
	const LucideKeySquare: typeof import('~icons/lucide/key-square')['default']
	const LucideLock: typeof import('~icons/lucide/lock')['default']
	const LucideMessageSquareDot: typeof import('~icons/lucide/message-square-dot')['default']
	const LucideMoon: typeof import('~icons/lucide/moon')['default']
	const LucidePanelTopInactive: typeof import('~icons/lucide/panel-top-inactive')['default']
	const LucidePocketKnife: typeof import('~icons/lucide/pocket-knife')['default']
	const LucideReceiptText: typeof import('~icons/lucide/receipt-text')['default']
	const LucideRefreshCw: typeof import('~icons/lucide/refresh-cw')['default']
	const LucideRocket: typeof import('~icons/lucide/rocket')['default']
	const LucideRows2: typeof import('~icons/lucide/rows2')['default']
	const LucideServer: typeof import('~icons/lucide/server')['default']
	const LucideShield: typeof import('~icons/lucide/shield')['default']
	const LucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
	const LucideStore: typeof import('~icons/lucide/store')['default']
	const LucideSun: typeof import('~icons/lucide/sun')['default']
	const LucideTrendingUp: typeof import('~icons/lucide/trending-up')['default']
	const LucideTrendingUpDown: typeof import('~icons/lucide/trending-up-down')['default']
	const LucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
	const LucideUser: typeof import('~icons/lucide/user')['default']
	const LucideUsers: typeof import('~icons/lucide/users')['default']
	const LucideWalletCards: typeof import('~icons/lucide/wallet-cards')['default']
	const LucideWeight: typeof import('~icons/lucide/weight')['default']
}
