---
- name: Update Agent Repository
  become: yes
  become_user: frappe
  command: 'git remote set-url upstream {{ agent_repository_url }}'
  args:
    chdir: /home/frappe/agent/repo

- name: Update Agent
  become: yes
  become_user: frappe
  command: /home/frappe/agent/env/bin/agent update
  args:
    chdir: /home/frappe/agent
  ignore_errors: yes

- name: Set Ownership of Agent Logs to Frappe user
  file:
    path: /home/frappe/agent/logs
    owner: frappe
    group: frappe
    recurse: yes

- name: Start Agent processes
  become: yes
  become_user: frappe
  command: 'sudo supervisorctl start agent:'
