---
- name: Install Kibana
  apt:
    name: kibana
    state: present
  register: apt_result
  until: apt_result.failed == false
  retries: 5
  delay: 120

- name: Setup Kibana
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

- name: Restart Kibana Daemon
  systemd:
    name: kibana
    daemon_reload: true
    enabled: yes
    state: restarted
