---
- name: Stop Fail2Ban
  service:
    name: fail2ban
    state: stopped

- name: Remove Fail2Ban
  apt:
    pkg: fail2ban
    state: absent
  register: apt_result
  until: apt_result.failed == false
  retries: 5
  delay: 120
