from typing import Final

from press.plans.server._types import ServerPlan, dedicated_instance_type, shared_instance_type

_do_server_plans: Final[list[ServerPlan]] = [
	{
		"name": "g-16vcpu-64gb-singapore-do-app",
		"title": "g-16vcpu-64gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 90900.0,
		"price_usd": 1010.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-16vcpu-64gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 16,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-16vcpu-64gb-singapore-do-db",
		"title": "g-16vcpu-64gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 90900.0,
		"price_usd": 1010.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-16vcpu-64gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 16,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-16vcpu-64gb-toronto-do-app",
		"title": "g-16vcpu-64gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 90900.0,
		"price_usd": 1010.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-16vcpu-64gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 16,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-16vcpu-64gb-toronto-do-db",
		"title": "g-16vcpu-64gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 90900.0,
		"price_usd": 1010.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-16vcpu-64gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 16,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-2vcpu-8gb-singapore-do-app",
		"title": "g-2vcpu-8gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-2vcpu-8gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 25,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-2vcpu-8gb-singapore-do-db",
		"title": "g-2vcpu-8gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-2vcpu-8gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 25,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-2vcpu-8gb-toronto-do-app",
		"title": "g-2vcpu-8gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-2vcpu-8gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 25,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-2vcpu-8gb-toronto-do-db",
		"title": "g-2vcpu-8gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-2vcpu-8gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 25,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-4vcpu-16gb-singapore-do-app",
		"title": "g-4vcpu-16gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 22500.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-4vcpu-16gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 16000,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-4vcpu-16gb-singapore-do-db",
		"title": "g-4vcpu-16gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 22500.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-4vcpu-16gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 16000,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-4vcpu-16gb-toronto-do-app",
		"title": "g-4vcpu-16gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 22500.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-4vcpu-16gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 16000,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-4vcpu-16gb-toronto-do-db",
		"title": "g-4vcpu-16gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 22500.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-4vcpu-16gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 16000,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-8vcpu-32gb-singapore-do-app",
		"title": "g-8vcpu-32gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 45000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-8vcpu-32gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-8vcpu-32gb-singapore-do-db",
		"title": "g-8vcpu-32gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 45000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "g-8vcpu-32gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-8vcpu-32gb-toronto-do-app",
		"title": "g-8vcpu-32gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 45000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-8vcpu-32gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "g-8vcpu-32gb-toronto-do-db",
		"title": "g-8vcpu-32gb",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 45000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "g-8vcpu-32gb",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-4gb-intel-singapore-do-app",
		"title": "s-2vcpu-4gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 5400.0,
		"price_usd": 60.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-2vcpu-4gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 4000,
		"disk": 80,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-4gb-intel-singapore-do-db",
		"title": "s-2vcpu-4gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 5400.0,
		"price_usd": 60.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-2vcpu-4gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 4000,
		"disk": 80,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-4gb-intel-toronto-do-app",
		"title": "s-2vcpu-4gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 5400.0,
		"price_usd": 60.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-2vcpu-4gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 4000,
		"disk": 80,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-4gb-intel-toronto-do-db",
		"title": "s-2vcpu-4gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 5400.0,
		"price_usd": 60.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-2vcpu-4gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 4000,
		"disk": 80,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-8gb-160gb-intel-singapore-do-app",
		"title": "s-2vcpu-8gb-160gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-2vcpu-8gb-160gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-8gb-160gb-intel-singapore-do-db",
		"title": "s-2vcpu-8gb-160gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-2vcpu-8gb-160gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-8gb-160gb-intel-toronto-do-app",
		"title": "s-2vcpu-8gb-160gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-2vcpu-8gb-160gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-2vcpu-8gb-160gb-intel-toronto-do-db",
		"title": "s-2vcpu-8gb-160gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-2vcpu-8gb-160gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 2,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-16gb-320gb-intel-singapore-do-app",
		"title": "s-4vcpu-16gb-320gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 19800.0,
		"price_usd": 220.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-16gb-320gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 16000,
		"disk": 320,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-16gb-320gb-intel-singapore-do-db",
		"title": "s-4vcpu-16gb-320gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 19800.0,
		"price_usd": 220.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-16gb-320gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 16000,
		"disk": 320,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-16gb-320gb-intel-toronto-do-app",
		"title": "s-4vcpu-16gb-320gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 19800.0,
		"price_usd": 220.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-16gb-320gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 16000,
		"disk": 320,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-16gb-320gb-intel-toronto-do-db",
		"title": "s-4vcpu-16gb-320gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 19800.0,
		"price_usd": 220.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-16gb-320gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 8,
		"memory": 16000,
		"disk": 320,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-240gb-intel-singapore-do-app",
		"title": "s-4vcpu-8gb-240gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-8gb-240gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 240,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-240gb-intel-singapore-do-db",
		"title": "s-4vcpu-8gb-240gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-8gb-240gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 240,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-240gb-intel-toronto-do-app",
		"title": "s-4vcpu-8gb-240gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-8gb-240gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 240,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-240gb-intel-toronto-do-db",
		"title": "s-4vcpu-8gb-240gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 11700.0,
		"price_usd": 130.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-8gb-240gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 240,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-intel-singapore-do-app",
		"title": "s-4vcpu-8gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9900.0,
		"price_usd": 110.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-8gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-intel-singapore-do-db",
		"title": "s-4vcpu-8gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9900.0,
		"price_usd": 110.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Singapore-DO",
		"instance_type": "s-4vcpu-8gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-intel-toronto-do-app",
		"title": "s-4vcpu-8gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9900.0,
		"price_usd": 110.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-8gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "s-4vcpu-8gb-intel-toronto-do-db",
		"title": "s-4vcpu-8gb-intel",
		"description": None,
		"plan_type": shared_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 9900.0,
		"price_usd": 110.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Toronto-DO",
		"instance_type": "s-4vcpu-8gb-intel",
		"platform": "x86_64",
		"cloud_provider": "DigitalOcean",
		"vcpu": 4,
		"memory": 8000,
		"disk": 160,
		"roles": ["Press Admin", "Press Member"],
	},
]
