from typing import Final

from press.plans.server._types import ServerPlan, dedicated_instance_type

_frappe_compute_server_plans: Final[list[ServerPlan]] = [
	{
		"name": "ccx13-frappe compute-app",
		"title": "ccx13",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 3000.0,
		"price_usd": 37.5,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX13",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 2,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx13-frappe compute-db",
		"title": "ccx13",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 3000.0,
		"price_usd": 37.5,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX13",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 2,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx23-frappe compute-app",
		"title": "ccx23",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 6000.0,
		"price_usd": 75.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX23",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 4,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx23-frappe compute-db",
		"title": "ccx23",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 6000.0,
		"price_usd": 75.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX23",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 4,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx33-frappe compute-app",
		"title": "ccx33",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12000.0,
		"price_usd": 150.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX33",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 8,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx33-frappe compute-db",
		"title": "ccx33",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12000.0,
		"price_usd": 150.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX33",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 8,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx43-frappe compute-app",
		"title": "ccx43",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 24000.0,
		"price_usd": 300.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX43",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 16,
		"memory": 65536,
		"disk": 800,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx43-frappe compute-db",
		"title": "ccx43",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 24000.0,
		"price_usd": 300.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX43",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 16,
		"memory": 65536,
		"disk": 800,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx53-frappe compute-app",
		"title": "ccx53",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 48000.0,
		"price_usd": 600.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX53",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 32,
		"memory": 131072,
		"disk": 1600,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx53-frappe compute-db",
		"title": "ccx53",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 48000.0,
		"price_usd": 600.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX53",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 32,
		"memory": 131072,
		"disk": 1600,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx63-frappe compute-app",
		"title": "CCX63",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 72000.0,
		"price_usd": 900.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX63",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 48,
		"memory": 196608,
		"disk": 2400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ccx63-frappe compute-db",
		"title": "ccx63",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"machine_unavailable": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 72000.0,
		"price_usd": 900.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Navi Mumbai",
		"instance_type": "CCX63",
		"platform": "x86_64",
		"cloud_provider": "Frappe Compute",
		"vcpu": 48,
		"memory": 196608,
		"disk": 2400,
		"roles": ["Press Admin", "Press Member"],
	},
]
