from typing import Final

from press.plans.server._types import ServerPlan, dedicated_instance_type

_oci_server_plans: Final[list[ServerPlan]] = [
	{
		"name": "16x128-af-johannesburg-1-app",
		"title": "16x128",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-af-johannesburg-1-app-premium",
		"title": "16x128-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 204800.0,
		"price_usd": 2560.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-af-johannesburg-1-db",
		"title": "16x128",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-af-johannesburg-1-db-premium",
		"title": "16x128-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 204800.0,
		"price_usd": 2560.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-me-jeddah-1-app",
		"title": "16x128",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-me-jeddah-1-app-premium",
		"title": "16x128-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 204800.0,
		"price_usd": 2560.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-me-jeddah-1-db",
		"title": "16x128",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x128-me-jeddah-1-db-premium",
		"title": "16x128-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 204800.0,
		"price_usd": 2560.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x128",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 131072,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-af-johannesburg-1-app",
		"title": "16x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-af-johannesburg-1-app-premium",
		"title": "16x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 128000.0,
		"price_usd": 1600.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-af-johannesburg-1-db",
		"title": "16x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-af-johannesburg-1-db-premium",
		"title": "16x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 128000.0,
		"price_usd": 1600.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-me-jeddah-1-app",
		"title": "16x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-me-jeddah-1-app-premium",
		"title": "16x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 128000.0,
		"price_usd": 1600.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-me-jeddah-1-db",
		"title": "16x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x32-me-jeddah-1-db-premium",
		"title": "16x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 128000.0,
		"price_usd": 1600.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 32768,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-af-johannesburg-1-app",
		"title": "16x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-af-johannesburg-1-app-premium",
		"title": "16x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 160000.0,
		"price_usd": 2000.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-af-johannesburg-1-db",
		"title": "16x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-af-johannesburg-1-db-premium",
		"title": "16x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 160000.0,
		"price_usd": 2000.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-me-jeddah-1-app",
		"title": "16x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-me-jeddah-1-app-premium",
		"title": "16x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 160000.0,
		"price_usd": 2000.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-me-jeddah-1-db",
		"title": "16x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "16x64-me-jeddah-1-db-premium",
		"title": "16x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 160000.0,
		"price_usd": 2000.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "16x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 16,
		"memory": 65536,
		"disk": 400,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-af-johannesburg-1-app",
		"title": "2x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12800.0,
		"price_usd": 160.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-af-johannesburg-1-db",
		"title": "2x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12800.0,
		"price_usd": 160.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-me-jeddah-1-app",
		"title": "2x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12800.0,
		"price_usd": 160.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-me-jeddah-1-app-premium",
		"title": "2x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-me-jeddah-1-db",
		"title": "2x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 12800.0,
		"price_usd": 160.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x16-me-jeddah-1-db-premium",
		"title": "2x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 16384,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-af-johannesburg-1-app",
		"title": "2x4",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 8000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-af-johannesburg-1-db",
		"title": "2x4",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 8000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-me-jeddah-1-app",
		"title": "2x4",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 8000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-me-jeddah-1-app-premium",
		"title": "2x4-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-me-jeddah-1-db",
		"title": "2x4",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 8000.0,
		"price_usd": 100.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x4-me-jeddah-1-db-premium",
		"title": "2x4-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x4",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 4096,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-af-johannesburg-1-app",
		"title": "2x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 10000.0,
		"price_usd": 125.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-af-johannesburg-1-db",
		"title": "2x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 10000.0,
		"price_usd": 125.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-me-jeddah-1-app",
		"title": "2x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 10000.0,
		"price_usd": 125.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-me-jeddah-1-app-premium",
		"title": "2x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-me-jeddah-1-db",
		"title": "2x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 10000.0,
		"price_usd": 125.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "2x8-me-jeddah-1-db-premium",
		"title": "2x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "2x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-af-johannesburg-1-app",
		"title": "4x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-af-johannesburg-1-app-premium",
		"title": "4x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-af-johannesburg-1-db",
		"title": "4x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-af-johannesburg-1-db-premium",
		"title": "4x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-me-jeddah-1-app",
		"title": "4x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-me-jeddah-1-app-premium",
		"title": "4x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-me-jeddah-1-db",
		"title": "4x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 20000.0,
		"price_usd": 250.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x16-me-jeddah-1-db-premium",
		"title": "4x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 16384,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-af-johannesburg-1-app",
		"title": "4x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-af-johannesburg-1-app-premium",
		"title": "4x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-af-johannesburg-1-db",
		"title": "4x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-af-johannesburg-1-db-premium",
		"title": "4x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-me-jeddah-1-app",
		"title": "4x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-me-jeddah-1-app-premium",
		"title": "4x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-me-jeddah-1-db",
		"title": "4x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 25600.0,
		"price_usd": 320.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x32-me-jeddah-1-db-premium",
		"title": "4x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 32768,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-af-johannesburg-1-app",
		"title": "4x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-af-johannesburg-1-app-premium",
		"title": "4x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-af-johannesburg-1-db",
		"title": "4x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-af-johannesburg-1-db-premium",
		"title": "4x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-me-jeddah-1-app",
		"title": "4x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-me-jeddah-1-app-premium",
		"title": "4x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-me-jeddah-1-db",
		"title": "4x8",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 16000.0,
		"price_usd": 200.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "4x8-me-jeddah-1-db-premium",
		"title": "4x8-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "4x8",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 4,
		"memory": 8192,
		"disk": 100,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-af-johannesburg-1-app",
		"title": "8x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-af-johannesburg-1-app-premium",
		"title": "8x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-af-johannesburg-1-db",
		"title": "8x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-af-johannesburg-1-db-premium",
		"title": "8x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-me-jeddah-1-app",
		"title": "8x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-me-jeddah-1-app-premium",
		"title": "8x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-me-jeddah-1-db",
		"title": "8x16",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 32000.0,
		"price_usd": 400.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x16-me-jeddah-1-db-premium",
		"title": "8x16-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 64000.0,
		"price_usd": 800.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x16",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 16384,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-af-johannesburg-1-app",
		"title": "8x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-af-johannesburg-1-app-premium",
		"title": "8x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-af-johannesburg-1-db",
		"title": "8x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-af-johannesburg-1-db-premium",
		"title": "8x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-me-jeddah-1-app",
		"title": "8x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-me-jeddah-1-app-premium",
		"title": "8x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-me-jeddah-1-db",
		"title": "8x32",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 40000.0,
		"price_usd": 500.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x32-me-jeddah-1-db-premium",
		"title": "8x32-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 80000.0,
		"price_usd": 1000.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x32",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 32768,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-af-johannesburg-1-app",
		"title": "8x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-af-johannesburg-1-app-premium",
		"title": "8x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "Johannesburg",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-af-johannesburg-1-db",
		"title": "8x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-af-johannesburg-1-db-premium",
		"title": "8x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "Johannesburg",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-me-jeddah-1-app",
		"title": "8x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 0,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-me-jeddah-1-app-premium",
		"title": "8x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 1,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 1,
		"server_type": "Server",
		"cluster": "KSA",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-me-jeddah-1-db",
		"title": "8x64",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 51200.0,
		"price_usd": 640.0,
		"premium": 0,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "8x64-me-jeddah-1-db-premium",
		"title": "8x64-Premium",
		"description": None,
		"plan_type": dedicated_instance_type,
		"enabled": 1,
		"legacy_plan": 0,
		"allow_unified_server": 0,
		"ignore_machine_availability_sync": 0,
		"price_inr": 102400.0,
		"price_usd": 1280.0,
		"premium": 1,
		"server_type": "Database Server",
		"cluster": "KSA",
		"instance_type": "8x64",
		"platform": "x86_64",
		"cloud_provider": "OCI",
		"vcpu": 8,
		"memory": 65536,
		"disk": 200,
		"roles": ["Press Admin", "Press Member"],
	},
]
