---
- name: Get network interface
  shell: ip route show default | awk '{for(i=1;i<=NF;i++) if ($i=="dev") print $(i+1)}' | head -n 1
  register: network_interface

- name: Add NAT gateway
  copy:
    dest: /etc/netplan/99-custom-gateway.yaml
    content: |
      network:
        ethernets:
          {{ network_interface.stdout }}:
            routes:
              - to: default
                via: {{ nat_gateway_ip }}
  when: nat_gateway_ip is defined and nat_gateway_ip

- name: Apply Netplan
  command: netplan apply
  when: nat_gateway_ip is defined and nat_gateway_ip
