---
- name: Download Sentry Self Hosting Archive
  become: yes
  become_user: frappe
  unarchive:
    src: https://github.com/getsentry/self-hosted/archive/refs/tags/24.4.2.tar.gz
    dest: /tmp
    remote_src: yes

- name: Stop Sentry
  become: yes
  become_user: frappe
  command: docker-compose down --remove-orphans
  args:
    chdir: /home/frappe/sentry

- name: Remove Sentry Directory
  become: yes
  become_user: frappe
  file:
    path: /home/frappe/sentry
    state: absent

- name: Create Sentry Directory
  become: yes
  become_user: frappe
  copy:
    src: /tmp/self-hosted-24.4.2/
    dest: /home/frappe/sentry
    remote_src: yes

- name: Create Sentry Environment File
  become: yes
  become_user: frappe
  template:
    src: ../../sentry/templates/sentry.env
    dest: /home/frappe/sentry/.env.custom

- name: Create Sentry Enhance Image File
  become: yes
  become_user: frappe
  template:
    src: ../../sentry/templates/enhance-image.sh
    dest: /home/frappe/sentry/sentry/enhance-image.sh
    mode: 0777

- name: Create Sentry YAML Config File
  become: yes
  become_user: frappe
  template:
    src: ../../sentry/templates/sentry.yml.jinja2
    dest: /home/frappe/sentry/sentry/config.yml

- name: Install Sentry
  become: yes
  become_user: frappe
  shell:
    cmd: echo "no" | bash install.sh --no-report-self-hosted-issues
    chdir: /home/frappe/sentry

- name: Create Sentry Python Config File
  become: yes
  become_user: frappe
  lineinfile:
    path: /home/frappe/sentry/sentry/sentry.conf.py
    line: "{{ lookup('template', '../../sentry/templates/sentry.conf.py') }}"

- name: Start Sentry
  become: yes
  become_user: frappe
  command: docker-compose --env-file /home/frappe/sentry/.env.custom up -d
  args:
    chdir: /home/frappe/sentry
