---
- name: Convert Frappe Server to Database Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: true
  roles:
    - role: convert
    - role: mysqld_exporter
    - role: deadlock_logger
