---
- name: Setup Deadman Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: bench
    - role: mariadb
    - role: essentials_deadman
    - role: deadman
