---
- name: Adds dummy 200MB file for deletion purposes
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Add 200MB file
      command: 'fallocate -l 200M /root/glass'
