---
- name: Setup Database Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: mirror
    - role: node_exporter
    - role: deadlock_logger
    - role: filebeat
    - role: clamav
    - role: aide
    - role: additional_process_hardening
    - role: warning_banners
    - role: auditd
    - role: sshd_hardening
    - role: pam
