---
- name: Setup NFS Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: docker
    - role: node_exporter
    - role: cadvisor
    - role: nfs_server
