---
- name: Check for security updates
  hosts: all
  roles:
    - role: security_update
      when: fetch_package_meta is not defined

    - role: fetch_package_meta
      when: fetch_package_meta | default(false) | bool

