---
- name: Setup Self Hosted Database Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: mariadb
    - role: nginx
    - role: agent
    - role: node_exporter
    - role: mysqld_exporter
    - role: deadlock_logger
    - role: filebeat
