- name: Setup Essentials for Self Hosted Database Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: node_exporter
    - role: filebeat