[Unit]
# This service reads files from the agent volume, so it must not start before the volume is mounted.
# BindsTo also stops this service if the mount stops.
# Reference: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#BindsTo=

After=home-frappe-agent.mount
BindsTo=home-frappe-agent.mount
