settings {
    logfile = "/var/log/on-prem-lsyncd-db/lsyncd.log",
    statusFile = "/var/log/on-prem-lsyncd-db/lsyncd.status"
}

sync {
    default.rsyncssh,
    source = "/var/lib/mysql",
    host = "root@{{ on_prem_ip }}",
    targetdir = "{{ database_base_directory }}/var/lib/mysql",
    delay = 1,
    rsync = {
        archive = true,
        compress = true,
        whole_file = false
    },
    ssh = {
        port = 22,
        options = {
            StrictHostKeyChecking = "no"
        }
    }
}

sync {
    default.rsyncssh,
    source = "/etc/mysql",
    host = "root@{{ on_prem_ip }}",
    targetdir = "{{ database_base_directory }}/etc/mysql",
    delay = 1,
    rsync = {
        archive = true,
        compress = true,
        whole_file = false
    },
    ssh = {
        port = 22,
        options = {
            StrictHostKeyChecking = "no"
        }
    }
}
