---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Check if ufw-docker exists
  ansible.builtin.stat:
    path: /usr/local/bin/ufw-docker
  register: ufw_docker_stat

- name: Get ufw-docker
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/chaifeng/ufw-docker/2b419bbdde946a4fd1a8651940ad95b6b0b96dfa/ufw-docker
    dest: /usr/local/bin/ufw-docker
    mode: '0755'
    checksum: sha256:16bc578c0cd78b7d44c53e5780c0d3d545860e428457a8910a3d2138fb225374
  become: true
  when: not ufw_docker_stat.stat.exists

- name: Reset ufw
  ufw:
    state: reset
  become: true

- name: Allow traffic by default
  ufw:
    default: allow
  become: true

- name: Disable ufw
  ufw:
    state: disabled
  become: true
  when: not (enabled | bool)

- name: Enable ufw
  ufw:
    state: enabled
  become: true
  when: enabled | bool

- name: Install ufw-docker
  ansible.builtin.command: ufw-docker install
  become: true
  when: enabled | bool

- name: Install ufw-docker service
  ansible.builtin.command: ufw-docker install-service --force
  become: true
  when: enabled | bool

- name: Bypass protected IPs
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    direction: 'in'
  loop: "{{ protected_ips }}"
  become: true
  when: enabled | bool

- name: Add rules
  ufw:
    rule: "{{ item.action | lower }}"
    from_ip: "{{ item.source | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.protocol | default(omit) | lower }}"
    direction: 'in'
  loop: "{{ rules }}"
  become: true
  when: enabled | bool
