---
- name: Create Netplan configuration for secondary IP
  copy:
    dest: /etc/netplan/60-secondary-ip.yaml
    mode: '0644'
    content: |
      network:
        ethernets:
          {{ ansible_default_ipv4.interface }}:
            dhcp4: true
            addresses:
              - {{ primary_ip }}/16
              - {{ secondary_ip }}/16
  when: secondary_ip is defined and secondary_ip

- name: Apply Netplan configuration
  command: netplan apply
  when: secondary_ip is defined and secondary_ip