[Service]
Environment=LD_PRELOAD={{libraries.files[0].path}}
{% if allocator == "tcmalloc" and tcmalloc_release_rate | default(0) | int >= 1 %}
Environment=TCMALLOC_RELEASE_RATE={{ tcmalloc_release_rate }}
{% endif %}
