from typing import Final

from press.plans.site import SitePlan

_site_plans: Final[list[SitePlan]] = [
	{
		"name": "Free",
		"enabled": 0,
		"document_type": "Site",
		"plan_title": "$0",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 48.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 0,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Trial",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 1.0,
		"max_database_usage": 512,
		"max_storage_usage": 5000,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Large",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 86000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": "No support",
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "SaaS Trial",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "SaaS Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 1.0,
		"max_database_usage": 500,
		"max_storage_usage": 5120,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Frappe Team",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Frappe Team",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 8.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Central Site",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Central Site",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ERPNext Trial",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "ERPNext Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 1.0,
		"max_database_usage": 500,
		"max_storage_usage": 5120,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - Low",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Small",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 8000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": "No support",
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ERPNextSMB Trial",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": None,
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 1.0,
		"max_database_usage": 500,
		"max_storage_usage": 5120,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Enterprise Basic",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Enterprise Basic",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 8.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Frappe Team High",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Frappe Team High",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 40960,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Enterprise Staging",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Enterprise Staging",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 4.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Central Site Higher",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Central Site Higher",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 48.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Enterprise Advanced",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Enterprise Advanced",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Large",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 86000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 1,
		"plan_description": "No support",
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - Supported",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Large Supported",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 36000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Enterprise Professional",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Enterprise Professional",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 12.0,
		"max_database_usage": 20480,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - DigitalOcean",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Large",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 86000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 1,
		"plan_description": "No support",
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - Low - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Small",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 8000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 0,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": "No support",
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Unlimited - Low - Supported",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Small Supported",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 8000.0,
		"max_database_usage": 512000,
		"max_storage_usage": 512000,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 1,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Enterprise Cloud 2020 (Yearly)",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "Enterprise Cloud 2020 (Yearly)",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 20480,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 1,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 5",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$5",
		"interval": "Daily",
		"price_inr": 410.0,
		"price_usd": 5.0,
		"cpu_time_per_day": 0.5,
		"max_database_usage": 250,
		"max_storage_usage": 2560,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 5 - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$5",
		"interval": "Daily",
		"price_inr": 410.0,
		"price_usd": 5.0,
		"cpu_time_per_day": 2.0,
		"max_database_usage": 1024,
		"max_storage_usage": 2560,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 1,
		"custom_hide_from_pricing_page": 1,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 10",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$10",
		"interval": "Daily",
		"price_inr": 820.0,
		"price_usd": 10.0,
		"cpu_time_per_day": 1.0,
		"max_database_usage": 500,
		"max_storage_usage": 5120,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 10 - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$10",
		"interval": "Daily",
		"price_inr": 820.0,
		"price_usd": 10.0,
		"cpu_time_per_day": 4.0,
		"max_database_usage": 2048,
		"max_storage_usage": 5120,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 1,
		"custom_hide_from_pricing_page": 1,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 25",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$25",
		"interval": "Daily",
		"price_inr": 2050.0,
		"price_usd": 25.0,
		"cpu_time_per_day": 2.0,
		"max_database_usage": 1024,
		"max_storage_usage": 25600,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 25 - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$25",
		"interval": "Daily",
		"price_inr": 2050.0,
		"price_usd": 25.0,
		"cpu_time_per_day": 8.0,
		"max_database_usage": 4096,
		"max_storage_usage": 25600,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 1,
		"custom_hide_from_pricing_page": 1,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 37.5",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$37.5",
		"interval": "Daily",
		"price_inr": 3075.0,
		"price_usd": 37.5,
		"cpu_time_per_day": 3.0,
		"max_database_usage": 1536,
		"max_storage_usage": 38400,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 37.5 - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$37.5",
		"interval": "Daily",
		"price_inr": 3075.0,
		"price_usd": 37.5,
		"cpu_time_per_day": 12.0,
		"max_database_usage": 6144,
		"max_storage_usage": 38400,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 1,
		"custom_hide_from_pricing_page": 1,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 50",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$50",
		"interval": "Daily",
		"price_inr": 4100.0,
		"price_usd": 50.0,
		"cpu_time_per_day": 4.0,
		"max_database_usage": 2048,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 50 - Hetzner",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$50",
		"interval": "Daily",
		"price_inr": 4100.0,
		"price_usd": 50.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 8192,
		"max_storage_usage": 51200,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 1,
		"custom_hide_from_pricing_page": 1,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 75",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$75",
		"interval": "Daily",
		"price_inr": 6150.0,
		"price_usd": 75.0,
		"cpu_time_per_day": 6.0,
		"max_database_usage": 3072,
		"max_storage_usage": 76800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 100",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$100",
		"interval": "Daily",
		"price_inr": 8200.0,
		"price_usd": 100.0,
		"cpu_time_per_day": 8.0,
		"max_database_usage": 4096,
		"max_storage_usage": 102400,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 150",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$150",
		"interval": "Daily",
		"price_inr": 12300.0,
		"price_usd": 150.0,
		"cpu_time_per_day": 12.0,
		"max_database_usage": 6144,
		"max_storage_usage": 153600,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 200",
		"enabled": 1,
		"document_type": "Site",
		"plan_title": "$200",
		"interval": "Daily",
		"price_inr": 16400.0,
		"price_usd": 200.0,
		"cpu_time_per_day": 16.0,
		"max_database_usage": 8192,
		"max_storage_usage": 204800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 300",
		"enabled": 0,
		"document_type": "Site",
		"plan_title": "$300",
		"interval": "Daily",
		"price_inr": 24600.0,
		"price_usd": 300.0,
		"cpu_time_per_day": 24.0,
		"max_database_usage": 12288,
		"max_storage_usage": 204800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 1,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 400",
		"enabled": 0,
		"document_type": "Site",
		"plan_title": "$400",
		"interval": "Daily",
		"price_inr": 32800.0,
		"price_usd": 400.0,
		"cpu_time_per_day": 32.0,
		"max_database_usage": 16384,
		"max_storage_usage": 204800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 1,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 500",
		"enabled": 0,
		"document_type": "Site",
		"plan_title": "$500",
		"interval": "Daily",
		"price_inr": 41000.0,
		"price_usd": 500.0,
		"cpu_time_per_day": 40.0,
		"max_database_usage": 20480,
		"max_storage_usage": 204800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 1,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "USD 1000",
		"enabled": 0,
		"document_type": "Site",
		"plan_title": "$1000",
		"interval": "Daily",
		"price_inr": 82000.0,
		"price_usd": 1000.0,
		"cpu_time_per_day": 80.0,
		"max_database_usage": 40960,
		"max_storage_usage": 204800,
		"is_trial_plan": 0,
		"offsite_backups": 1,
		"private_benches": 1,
		"database_access": 1,
		"monitor_access": 1,
		"support_included": 1,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	# {'Frappe Desk Free', 'Professional SMB', 'm6i.large-ap-south-1-app', 'ERPNext Test Trial', 'Essential SMB', 'ERPNext SMB Trial', 'FC $ 10'}
	# These are legacy plans which are no more used in active sites but archived sites have them
	{
		"name": "Frappe Desk Free",
		"enabled": 0,
		"document_type": "Marketplace App",
		"plan_title": "FrappeDesk Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Professional SMB",
		"enabled": 0,
		"document_type": "Saas App",
		"plan_title": "Professional",
		"interval": "Monthly",
		"price_inr": 37500.0,
		"price_usd": 500.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "m6i.large-ap-south-1-app",
		"enabled": 0,
		"document_type": "Server",
		"plan_title": "m6i.large",
		"interval": "Daily",
		"price_inr": 12000.0,
		"price_usd": 150.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": "Mumbai",
		"instance_type": "m6i.large",
		"vcpu": 2,
		"memory": 8192,
		"disk": 50,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ERPNext Test Trial",
		"enabled": 0,
		"document_type": "Saas App",
		"plan_title": "ERPNext Test Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "Essential SMB",
		"enabled": 0,
		"document_type": "Saas App",
		"plan_title": "Essential",
		"interval": "Monthly",
		"price_inr": 22500.0,
		"price_usd": 300.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "ERPNext SMB Trial",
		"enabled": 0,
		"document_type": "Saas App",
		"plan_title": "ERPNext SMB Trial",
		"interval": "Daily",
		"price_inr": 0.0,
		"price_usd": 0.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 1,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
	{
		"name": "FC $ 10",
		"enabled": 0,
		"document_type": "Marketplace App",
		"plan_title": "FC USD 10",
		"interval": "Daily",
		"price_inr": 750.0,
		"price_usd": 10.0,
		"cpu_time_per_day": 0.0,
		"max_database_usage": 0,
		"max_storage_usage": 0,
		"is_trial_plan": 0,
		"offsite_backups": 0,
		"private_benches": 0,
		"database_access": 0,
		"monitor_access": 0,
		"support_included": 0,
		"dedicated_server_plan": 0,
		"is_frappe_plan": 0,
		"cluster": None,
		"instance_type": None,
		"vcpu": 0,
		"memory": 0,
		"disk": 0,
		"allow_downgrading_from_other_plan": 1,
		"legacy_plan": 0,
		"private_bench_support": 0,
		"custom_hide_from_pricing_page": 0,
		"plan_description": None,
		"restrict_based_on_dedicated_server_plan": 0,
		"minimum_server_price_usd": 0.0,
		"cloud_providers": ["AWS EC2", "OCI"],
		"release_groups": [],
		"allowed_apps": [],
		"roles": ["Press Admin", "Press Member"],
	},
]
