---
- name: Perform Final Sync
  block:
    - name: Stop On-Premise Lsyncd service
      systemd:
        name: on-prem-lsyncd-db
        state: stopped

    - name: Create and drop a random database to generate GTID
      shell: |
        DB_NAME="dummy_db_$(date +%s)"
        mysql -uroot -p'{{ mariadb_root_password }}' -e "CREATE DATABASE ${DB_NAME}; DROP DATABASE ${DB_NAME};"
      changed_when: true

    - name: Capture current master GTID
      shell: "mysql -uroot -p'{{ mariadb_root_password }}' -N -B -e \"SELECT @@GLOBAL.gtid_current_pos;\""
      register: master_gtid
      changed_when: false

    - name: Stop MariaDB service
      systemd:
        name: mariadb
        state: stopped

    - name: Save GTID to file
      copy:
        content: "{{ master_gtid.stdout }}"
        dest: "/tmp/master_gtid.txt"

    - name: Copy GTID file to remote base directory
      command: "scp -o BatchMode=yes -o StrictHostKeyChecking=no -P 22 /tmp/master_gtid.txt root@{{ on_prem_ip }}:{{ database_base_directory }}/master_gtid.txt"

    - name: Replace bind-address IP in config file
      ansible.builtin.replace:
        path: /etc/mysql/conf.d/frappe.cnf
        regexp: '^bind-address\s*=\s*.*'
        replace: 'bind-address = {{ mariadb_bind_address }}'
      when: mariadb_bind_address is defined and mariadb_bind_address != ""

    - name: Flush filesystem buffers
      command: sync

    - name: Remove database container from on-prem server if exists
      command: "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p 22 root@{{ on_prem_ip }} 'docker rm -f fc-dr-db-replica || true'"

    - name: Final Rsync for /var/lib/mysql
      command: "rsync -a --delete -e 'ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p 22' /var/lib/mysql/ root@{{ on_prem_ip }}:{{ database_base_directory }}/var/lib/mysql/"
      # 30 minute timeout
      async: 1800
      poll: 10

    - name: Final Rsync for /etc/mysql
      command: "rsync -a --delete -e 'ssh -o BatchMode=yes -o StrictHostKeyChecking=no -p 22' /etc/mysql/ root@{{ on_prem_ip }}:{{ database_base_directory }}/etc/mysql/"
  always:
    - name: Start MariaDB service
      systemd:
        name: mariadb
        state: started
