---
- name: Setup Agent TLS (Private Key)
  become: yes
  become_user: frappe
  copy:
    content: "{{ certificate_private_key }}"
    dest: /home/frappe/agent/tls/privkey.pem

- name: Setup Agent TLS (Full Chain)
  become: yes
  become_user: frappe
  copy:
    content: "{{ certificate_full_chain }}"
    dest: /home/frappe/agent/tls/fullchain.pem

- name: Setup Agent TLS (Intermediate Chain)
  become: yes
  become_user: frappe
  copy:
    content: "{{ certificate_intermediate_chain }}"
    dest: /home/frappe/agent/tls/chain.pem

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
