[Interface]
Address = {{ wireguard_network }}
ListenPort = {{ wireguard_port }}
PrivateKey = {{ wireguard_private_key }}

PreUp = sysctl -w net.ipv4.ip_forward=1

{% if external_interface_id | default(false) %}
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ external_interface_id }} -j MASQUERADE
PostUp = iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ external_interface_id }} -j MASQUERADE
{% else %}

PostUp = iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT

PostDown = iptables -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT

{% endif %}
PostDown = sysctl -w net.ipv4.ip_forward=0

{% if peers %}
{% for peer in (peers | from_json) %}
[Peer]
# {{ peer.name }}
{% if peer.peer_ip %}
Endpoint = {{peer.peer_ip}}:{{wireguard_port}}
{% endif %}
PublicKey = {{ peer.public_key }}
AllowedIPs = {{ peer.allowed_ips}}
PersistentKeepalive = 25

{% endfor %}
{% endif %}